### PR TITLE
Adds an API to MOT

### PR DESCRIPTION
**Pull request by gregcube**
This PR adds a public, read-only API to the MOT, allowing developers to retrieve model data in JSON format.  See API.md for endpoints and other info.

If you're updating a local MOT instance, run a Drupal database update after pulling/merging.  You can do that via drush on the command line, e.g. run `vendor/bin/drush updb` from the MOT project root, or via the browser, e.g. access `https://mot.local/update.php`.  This db update enables API dependencies and adds the proper API configuration and permissions.  This happens automatically on mot.isitopen.ai using github workflows.

### CODE REVIEW

**Review by lehors — COMMENTED** [review]
Looks great but trying it locally I'm getting an access error:
```
curl 127.0.0.1:8888/api/v1/models
{"error":{"code":403,"message":"The \u0027restful get model_v1\u0027 permission is required."}}
```
Any idea what's wrong?

**Comment by gregcube** [comment]
> Looks great but trying it locally I'm getting an access error:
> 
> ```
> curl 127.0.0.1:8888/api/v1/models
> {"error":{"code":403,"message":"The \u0027restful get model_v1\u0027 permission is required."}}
> ```
> 
> Any idea what's wrong?

Appears the anonymous role is missing permission to access the API endpoints.

Browse to `/admin/people/permissions/anonymous` and make sure `Access GET on Model v1 resource` is checked.

This should've been applied when running the database update.

**Comment by lehors** [comment]
Indeed, that permission wasn't set and setting it solves the problem. Is there a configuration file this should be added to or do we have to do that manually after merging?

**Comment by gregcube** [comment]
The permission should be set automatically when running the database update, and it has worked in my 2 test environments when deploying via github actions. I suggest we try and see what happens.

**Comment by lehors** [comment]
ok.

**Pull request merged**
