### PR TITLE
Tackles issue 10, 11, 16 and 17

### PR DESCRIPTION
**Pull request by gregcube**
This PR addresses a few issues.  Breakdown below.

Issue #10:
Models can now be added/ updated via PRs.
This includes a model schema and validation script to ensure models pass before import.
All current models in the MOT have been YAML-ized and added in the models directory.
See CONTRIBUTING.md for documentation on the process.

Issue #11:
Automatic builds and deployments now work from the main branch.
Deployment can also be manually invoked via the actions tab.
See DEPLOY.md for details on the process.

Issue #16 and Issue #17:
A session is now created when evaluating a model, and input values are saved.
These input values can be reused when retrying model evaluation, or when submitting a model via the website.
The option to `Retry` and `Submit model` are displayed on the evaluation results page.
A `Start over` button is provided on the evaluate model page, which destroys the current session, if one exists.

I've also updated INSTALL.md, adding instructions for populating the MOT database with the YAML models, and added a TRUSTED_HOST environment variable to fix a Drupal status warning.

### CODE REVIEW

**Comment by lehors** [comment]
This looks like a great step forward. I'm running it locally on my computer and reviewing the changes. Stay tuned.

**Comment by gregcube** [comment]
> Sounds good! Small thing: Wonder if we should change `Start over` to `Restart evaluation` for clarity?

Makes sense. I vote for this change.

**Comment by gregcube** [comment]
> With all that being said I think we'll need another piece which is to sync the model files in the repo with the database so that when a model is submitted or possibly modified online the changes get reflected in the repo.
> 
> I don't know @gregcube whether you've thought about this at all but I'm happy to defer this for now and merge this as is

I wrote a script that generates YAML models from the Drupal database. With some additional work and cleanup, we could integrate this functionality. It might be useful to create a new issue thread to discuss the details and implementation.

I'm happy to proceed with the merge as is. After it's merged, I'll manually trigger the workflows to ensure the production and stage environments are properly configured. If everything runs smoothly and it makes sense to you, I'll submit a simple PR to change the `Start over` button to `Restart evaluation`, which will help test the automated deployment workflow.

**Comment by lehors** [comment]
Sounds good to me. Let's start with merging this PR.

**Review by lehors — APPROVED** [review]

**Pull request merged**
